### ISSUE TITLE
Alert User Whether They Have Account

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#21]
Understanding the potential vulnerability of the system returning a "You do not have an account" message to users, we feel this is causing enough problems that we want this done especially in Year 1 when many of our users are resetting passwords for accounts that do not exist.

**Comment by cameroneickmeyer** [comment]
Idea: Could "invalid credentials" text be modified to "Invalid Credentials. Are you sure you have an account? This system is new for the 2017-18 Season. Try Creating an Account."

**Comment by cameroneickmeyer** [comment]
Idea 2: Can we move "Create Account" button above the login for just this season? We're trying to hit them over the head with it just to get everyone onboard.

**Comment by sn-np** [comment]
I just moved the "Create Account" button to be above the sign in (and added more text explaining). I also added text to the lost password page to make it clear that they have to create an account before a reset will do anything.

And then I also updated the error message on invalid credentials to indicate they should try creating an account rather than resetting a password.

**Comment by cameroneickmeyer** [comment]
OK. Thanks. Let's chat through on Thursday the pros/cons of the larger ping to the system to see if an account exists.

**Comment by sn-np** [comment]
Done?
