### ISSUE TITLE
Minimum Age Limit for Coaching Courses

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#42]
We MUST have minimum age limit hard coded to be 18 for ALL coaching courses regardless of level. Officials can be more flexible but coaches are all 18+

**Comment by cameroneickmeyer** [comment]
Ideally we can have assistance to make this change to all courses that have already been created.

**Comment by sn-np** [comment]
How are coaching memberships being created if the person isn't 18? I assumed that if they had a valid membership confirmation from Ralph then their age had already been verified.

**Comment by cameroneickmeyer** [comment]
Player/Coach is the member type so technically a U18 kid who's a player has a coaching membership. It might not be a huge problem but the easiest fix is a hard 18+ stop in the system.

**Comment by sn-np** [comment]
I've updated the system so the student must be 18 in order to register for a Coaching course. I left it so they can create an account even if they aren't 18 yet figuring that students who turn 18 in the spring may already have a player/coach registration in the fall. This way their parent can create their account in the fall (when everyone's numbers are still easy to recall), and then as soon as the student is 18 they can register for a course (seemed like the path of least resistance). If we want to prevent account creation we can go back and do that, but I think this serves the purpose you wanted.

I did a search attempting to find people who are not yet 18 who are registered for a coaching course (the cutoff I used was a birth date of 1999-08-01). If I did everything right (there were a lot of steps!) there is only one:

Zachary Biren born 2000-12-01 is registered for NY Hempstead CEP 1 on Sept 10.
