### ISSUE TITLE
User unable to access account

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#8]
This user has an active account but resetting password no longer works. I've confirmed as well.

From: noreply@courses.usahockey.com <noreply@courses.usahockey.com> on behalf of USA Hockey Courses <noreply@courses.usahockey.com>
Sent: Wednesday, July 12, 2017 9:47 AM
To: brianmellon@hotmail.com
Subject: Password reset
 
Dear USA Hockey Coach or Official,
We received a request to reset your password for courses.usahockey.com. Click the link below to reset your password.
Reset here

If you cannot click on the link, copy and paste the following into your browser:
courses.usahockey.com/app/reset/password_reset?token=12C591DA-6711-11E7-8C64-D6338B03E63F

Please note: this link will expire after 2 hours and you will need to submit a new password reset request to get a new link.
Thank you for your dedication to hockey,

**Comment by sn-np** [comment]
The token in this e-mail is invalid -- too old. 

I just used the token directly from the database to create a new password for him and it went through fine. I can either tell you the password I used for him, or he can generate a new token by doing a new reset password request and making sure to use the new link.

**Comment by cameroneickmeyer** [comment]
Tell me the password and I can have him reset. Are there any steps we can take to try to close this process/loophole up? We're in pretty early stages and I think this is going to be one of our biggest tech support issues.

**Comment by sn-np** [comment]
Send e-mail with the password.

In terms of closing the loop we probably need to bring Richard and/or Andrew in to see what they know of best practices. I didn't actually do anything here except see that the token in the database didn't match the one in the e-mail, meaning that the user wasn't using the most recently generated token.

**Comment by cameroneickmeyer** [comment]
Here's another one where he's locked out and resetting the password doesn't work. Can we clear his out please?


YI | ANDREW | peaciter@sbcglobal.net | 186801773YIAND
-- | -- | -- | --

**Comment by cameroneickmeyer** [comment]
I think I've found a pattern. User DOES NOT have an account but resets password, they then try multiple times to reset and don't get in. At that point they CREATE an account but the system does not let them in at that point either and they next ask for a NEW password. Somewhere in that process we have our bug.

**Comment by cameroneickmeyer** [comment]
Latest user with the problem: 

SCOTT | MARK | dakotacory@yahoo.com | 259702395SCOTT
-- | -- | -- | --

**Comment by sn-np** [comment]
I'm not sure what you mean by "clear out"? Do you mean get rid of the failed attempts to log in? Or remove the account completely so they can start from scratch? I've removed Mark's failed attempts so he won't hit the timeout anymore.

Neither Andrew nor Mark has a live password reset token (not surprising since you sent this yesterday), but Andrew managed to login late last night or early this morning based on the logs, so he must have actually used his successfully.

The account creation and password reset processes are really separate things, so there shouldn't be any interaction between them.  As discussed before, a reset will have no effect in the system if there isn't already account, except that when the user tries to login using their "reset but non-existent" credentials it will be logged as a failed attempt, eventually resulting in the timeout.  

Here is what I propose: I update the code so that when a user creates an account, their failed attempt count goes to zero. This should mean that new accounts are always given a blank slate in terms of logging in, and they shouldn't need to do a password reset (I mean, they didn't need to before either, but this will just be an extra layer of protection from themselves).  That work for you?
