### ISSUE TITLE
Public search pages not filtering

### ISSUE THREAD

**Issue by cameroneickmeyer** [cameroneickmeyer/CoursesSystem#96]
The embedded search URLs are not filtering to Officiating/Coaching and showing both

**Comment by sn-np** [comment]
This one will take me a minute (and I have another commitment for the next few hours). Can you please let me know what the embed link is? That'll help me test before I respond again.

**Comment by cameroneickmeyer** [comment]
No rush (slow season) https://courses.usahockey.com/external/search.html?type=coaching 

https://courses.usahockey.com/external/search.html?type=officiating

**Comment by sn-np** [comment]
The easiest fix here is to update the link to capitalize the type of the search like below:
https://courses.usahockey.com/external/search.html?type=Coaching
https://courses.usahockey.com/external/search.html?type=Officiating

One other thing to keep in mind while testing: if you are logged in in another window, your session cookie comes along for the ride, which would cause old events to show instead of just future ones (I ran into this one doing my own testing).
